# Uncomment the next line to define a global platform for your project

target 'Chat' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Chat

  target 'ChatTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'ChatUITests' do
    # Pods for testing
  end

pod 'Firebase/Core'
pod 'Firebase/Auth'
pod 'Firebase/Database'
pod 'FirebaseFirestore'

end
